---
  - name: just update repo and recreate flask container
    hosts: aws
    become: yes
    tasks:
      - name: pull from aiblogger repo
        ansible.builtin.git:
          repo: 'https://github.com/BohdanBykov/aiblogger'
          dest: '/home/ubuntu/aiblogger'
          force: yes
          update: yes
          version: master

      - name: recreate flask container
        ansible.builtin.shell: docker compose up -d --force-recreate --build flask
        args:
          chdir: /home/ubuntu/aiblogger/ops
