global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: node
    static_configs:
      - targets: ["172.22.0.2:9100"]

# remote_write:
#   - url: https://prometheus-us-central1.grafana.net/api/prom/push
#     basic_auth:
#       username: 667449
#       password: stack-483338-easystart-prom-publisher
