version: '3'

services:
  flask:
    build: 
      context: ../
      dockerfile: Dockerfile
    environment:
      - CONFIG=$CONFIG
      - DBHOST=$DBHOST
      - DBPASS=$DBPASS
      - SECRET_KEY=$SECRET_KEY

    command: sh -c "cd /aiblogger && gunicorn --bind 0.0.0.0:8000 wsgi:app"
    networks:
      ainet:
        ipv4_address: 172.18.0.3   
    expose:
      - '3306'
      - '8000'

  ngx:
    image: nginx
    networks:
      ainet:
        ipv4_address: 172.18.0.4
    ports:
      - 80:80
    volumes:
      - /srv/aiblogger/nginx.conf:/etc/nginx/nginx.conf
      - /srv/aiblogger/nginx_logs:/var/log/nginx

networks:
  ainet:
    ipam:
      config:
       - subnet: 172.18.0.0/16


