version: '3'

services:

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      ainet:
        ipv4_address: 172.18.0.2
    expose:
      - '3306'
    volumes:
      - /srv/aiblogger/mysql:/var/lib/mysql
 
  flask:
    build: 
      context: ../
      dockerfile: Dockerfile
    environment:
      - CONFIG=Docker
    command: sh -c "gunicorn --bind 0.0.0.0:8000 wsgi:app"
    networks:
      ainet:
        ipv4_address: 172.18.0.3   
    expose:
      - '3306'
      - '8000'

  ngx:
    image: nginx
    networks:
      ainet:
        ipv4_address: 172.18.0.4
    ports:
      - 80:80
    volumes:
      - /srv/aiblogger/nginx.conf:/etc/nginx/nginx.conf
      - /srv/aiblogger/:/var/log/nginx

networks:
  ainet:
    ipam:
      config:
       - subnet: 172.18.0.0/16


