pipeline {
    agent any 
    stages {
        stage('run playbook') { 
            steps {
            
                ansiblePlaybook(
                    playbook: 'ops/ansible_playbooks/docker_update_dev.yaml',
                    hostKeyChecking: false,
                    )
            
            }
        }
    }
}