// node {
//     ansiblePlaybook( 
//         playbook: 'ops/deploy_on_docker.yaml',
//         hostPattern: 'vm',
//         become: true, 
//         hostKeyChecking: false
//         )
// }

pipeline {
    agent any 
    stages {
        stage('run playbook') { 
            steps {
                ansiblePlaybook(
                    playbook: 'ops/update_on_docker.yaml',
                    hostKeyChecking: false,
                    hostPattern: 'vm',
                    become: true
                    )
                } 
            }
        }
    }
}